### ISSUE TITLE
Speaker doesn't play full audio

### ISSUE THREAD

**Issue by ttseng** [lioujj/pxt-mp3#1]
Thank you for writing this extension.

I am trying it out but am running into issues playing the audio file fully.  The mp3 plays for a fraction of a second but then a low buzzing noise is heard.

Right now, I have a single file on my microSD card titled `001` that contains three audio files `001.mp3`, `002.mp3`, and `003.mp3`

![image](https://user-images.githubusercontent.com/519336/73639299-6ec75600-46af-11ea-86be-9d77046490c2.png)

My circuit exactly follows the diagram in your README:
![image](https://user-images.githubusercontent.com/519336/73638375-9d443180-46ad-11ea-83fc-f4f7bceea3dd.png)

And my Microsoft Makecode example is pretty simple - depending on which button is pressed, the speaker should play a different audio file on the card:
![image](https://user-images.githubusercontent.com/519336/73638437-bc42c380-46ad-11ea-8663-db81b6bd191a.png)

I have confirmed that the speaker itself works, which I tested by playing a basic melody.  

However, when I attempt to play the audio, the beginning of the clip plays for a fraction of a second, and then a buzzing noise is heard for about ~3 seconds.  (the clips are about 2 seconds each). A video of the problem can be found here: https://youtu.be/D26L7jboNTg

Do you have any ideas what might be wrong?  Also, would it be possible to include a link to some audio files you used so I can test your exact setup?

Thank you!

**Comment by ttseng** [comment]
Note that I also made sure to remove any hidden files, as per the instructions here: https://wiki.dfrobot.com/DFPlayer_Mini_SKU_DFR0299

```
NOTE: If you are using Mac OS X to copy the mp3, the file system will automatically add hidden files like: "._0001.mp3" for index, which this module will handle as valid mp3 files. It is really annoying. So you can run following command in terminal to eliminate those files.

dot_clean /Volumes/<SDVolumeName>
Please replace the to the volume name of your SD card.
```
![image](https://user-images.githubusercontent.com/519336/73640498-b2bb5a80-46b1-11ea-872b-b7e11eea874d.png)

**Comment by ttseng** [comment]
I find that if I power the Microbit using the 3V output of an Arduino, then the sound works fine.  Perhaps this is a power-related problem, then?

Here is a video: https://www.youtube.com/watch?v=t3do5nsMikE&feature=youtu.be

**Comment by lioujj** [comment]
This issue has been done.
